### GENERAL SETTINGS ###

# Site settings
title: CocoaHeads Belo Horizonte
description: "Comunidade mineira de desenvolvedores iOS"
analytics:
baseurl: "" #important: start with /
url: "http://cocoaheadsbh.com.br"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#e7e7e7" #"#F70031"
  primary_rgb: "231,231,231" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#004832" #"#33004D"
  link: "#608b59"
  link_hover: "#e7e7e7"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/CocoaHeadsBrasil/
  - title: twitter
    url: https://twitter.com/CocoaHeadsBr
  - title: instagram
    url: https://www.instagram.com/cocoaheadsbr/
  - title: youtube
    url: https://www.youtube.com/channel/UCgxgHAknB-xGCRGU6tjQI9w

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
email: hello@solidtheme.com
tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Salmo Junior
    position: Chapter Leader
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: salmo.jpg
    social:
      - title: envelope #use for email address
        url: mailto:junior.salmo@gmail.com
      - title: twitter
        url: https://twitter.com/SalmoJr
  - name: Marcilio Junior
    position: Co-Organizer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: marcilio.jpg
    social:
      - title: envelope #use for email address
        url: mailto:marciliojrs@gmail.com
      - title: twitter
        url: https://twitter.com/marciliojrs
  - name: Gabriel Oliva
    position: Co-Organizer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: gabriel.jpg
    social:
      - title: envelope #use for email address
        url: mailto:gfpoliva@gmail.com
      - title: twitter
        url: http://twitter.com/gabrieloliva_

# Clients information. Shown on Home and About pages.
clients:
  - name: CI&T
    img: ciandt.jpeg
  - name: Novatec
    img: novatec.jpeg
  - name: Avenue Code
    img: avenuecode.jpeg
  - name: ThoughtWorks
    img: tw.jpeg

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "CocoaHeads é um grupo formado por desenvolvedores (profissionais e iniciantes), que se organizam para reunir pessoas com a mesma paixão: Programação para os iDevices da Apple (OSX e iOS)."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: ""
    author:
    position:
